[build]
target = "./x86_64-unknown-none-elf.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none-elf]
runner = ["/bin/bash", "-c", "cargo make --cwd .. -e MAKE_PROFILE=test run"]
