[env]
IMAGE = "disk.img"

[tasks.mkimage]
dependencies = [{ name = "efi", path = "bootloader" }]
script_runner = "@shell"
script = '''
rm "${IMAGE}" || true
qemu-img create -f raw "${IMAGE}" 200M
mkfs.fat -n "MANDARIN OS" -s 2 -f 2 -F 32 -R 32 "${IMAGE}"
mkdir -p ./mnt
sudo mount -o loop "${IMAGE}" ./mnt
sudo mkdir -p ./mnt/EFI/BOOT
sudo cp ./bootloader/BOOTX64.EFI ./mnt/EFI/BOOT/BOOTX64.EFI
sudo umount ./mnt
'''

[tasks.run]
dependencies = ["mkimage"]
script_runner = "@shell"
script = '''
qemu-system-x86_64 \
	-drive if=pflash,format=raw,file=./uefi-firmware/OVMF_CODE.fd \
	-drive if=pflash,format=raw,file=./uefi-firmware/OVMF_VARS.fd \
	-drive format=raw,media=disk,index=0,file=disk.img \
    -device isa-debug-exit
'''

[tasks.clean]
clear = true
ignore_errors = true
dependencies = [{ name = "clean", path = "bootloader" }]
script = "rm ${IMAGE}"
