[tasks.build]
script = '''
#!/usr/bin/env bash
echo ${MAKE_PROFILE}
case ${MAKE_PROFILE} in
    "release")
        cargo build --release ;;
    "test")
        cargo test --no-default-features --no-run ;;
    "test-console")
        cargo test --no-run ;;
    *)
        cargo build ;;
esac
'''

[tasks.check]
script = "cargo clippy"

[tasks.clean]
dependencies = ["cargo-clean", "remove-elf"]

[tasks.cargo-clean]
script = "cargo clean"

[tasks.remove-elf]
ignore_errors = true
script = "rm ./kernel.elf"

[config]
skip_core_tasks = true

[tasks.default]
alias = "build"
