[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.check]
command = "cargo"
args = ["clippy"]

[tasks.clean]
dependencies = ["cargo-clean", "remove-elf"]

[tasks.cargo-clean]
command = "cargo"
args = ["clean"]

[tasks.remove-elf]
ignore_errors = true
command = "rm"
args = ["./kernel.elf"]

[config]
skip_core_tasks = true

[tasks.default]
alias = "build"
