[tasks.build]
script = "cargo build --release"

[tasks.check]
script = "cargo clippy"

[tasks.clean]
dependencies = ["cargo-clean", "remove-elf"]

[tasks.cargo-clean]
script = "cargo clean"

[tasks.remove-elf]
ignore_errors = true
script = "rm ./kernel.elf"

[config]
skip_core_tasks = true

[tasks.default]
alias = "build"
