[env]
TARGET_DIR = "./target/x86_64-unknown-uefi"

[tasks.build]
script = "cargo build --release"

[tasks.check]
script = "cargo clippy"

[tasks.copy-efi]
dependencies = ["build"]
script = "cp ${TARGET_DIR}/release/bootloader.efi ./BOOTX64.EFI"

[tasks.clean]
dependencies = ["cargo-clean", "remove-efi"]

[tasks.cargo-clean]
script = "cargo clean"

[tasks.remove-efi]
ignore_errors = true
script = "rm ./BOOTX64.EFI"

[config]
skip_core_tasks = true

[tasks.default]
alias = "copy-efi"
