[env]
TARGET_DIR = "./target/x86_64-unknown-uefi/release"

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.copy-efi]
dependencies = ["build"]
script = "cp ${TARGET_DIR}/bootloader.efi ./BOOTX64.EFI"

[tasks.clean]
dependencies = ["cargo-clean", "remove-efi"]

[tasks.cargo-clean]
command = "cargo"
args = ["clean"]

[tasks.remove-efi]
ignore_errors = true
command = "rm"
args = ["./BOOTX64.EFI"]

[config]
skip_core_tasks = true

[tasks.default]
alias = "copy-efi"
